# Generated by Django 3.0.7 on 2020-07-08 06:41

from django.db import migrations, models
import django

import django.utils.timezone
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrolNoktasi', models.TextField(blank=True, max_length=60)),
                ('kritiklik', models.CharField(max_length=10)),
                ('frekans', models.IntegerField(default='')),
                ('kontrolMetod', models.TextField(blank=True, max_length=100)),
               
            ],
            
        ),
       
    ]
