# Generated by Django 3.0.7 on 2020-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controltable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltable',
            name='atolye',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='controltable',
            name='ca',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='controltable',
            name='cuet',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='controltable',
            name='uet',
            field=models.TextField(default='', max_length=50),
        ),
    ]
