# Generated by Django 3.0.7 on 2020-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controltable', '0002_auto_20200708_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltable',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
