# Generated by Django 3.0.7 on 2020-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controltable', '0003_controltable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltable',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
