# Generated by Django 3.0.7 on 2020-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controltable', '0004_auto_20200708_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltable',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
