# Generated by Django 3.0.7 on 2020-07-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controltable', '0005_auto_20200708_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controltable',
            name='date',
        ),
    ]
